spring.application.name=usuarioService

#Datasource / Database
spring.datasource.url=jdbc:oracle:thin:@proyectolibroasistencia_high?TNS_ADMIN=C:/Users/Herimar/IdeaProjects/ms-usuario/usuarioService/src/main/resources/wallet/Wallet_proyectoLibroAsistencia
spring.datasource.username=ms_usuario
spring.datasource.password=Microservicio_usuario1.
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
